/*
 *
 * SinglePostPage constants
 *
 */


export const LOAD_ARCHIVEDATA = 'ez2/ArchivePage/LOAD_ARCHIVEDATA';
export const LOAD_ARCHIVEDATA_SUCCESS = 'ez2/ArchivePage/LOAD_ARCHIVEDATA_SUCCESS';
export const LOAD_ARCHIVEDATA_FAILURE = 'ez2/ArchivePage/LOAD_ARCHIVEDATA_FAILURE';

export const SET_CURRENTLYDISPLAYEDCHUNKINDEX = 'app/ArchivePage/SET_CURRENTLYDISPLAYEDITEMINDEX';

export const SET_CURRENTLYDISPLAYEDCHUNKDATA = 'app/ArchivePage/SET_CURRENTLYDISPLAYEDCHUNKDATA';
export const SAVE_INITIALPAGENUMBER = 'app/ArchivePage/SAVE_INITIALPAGENUMBER';

export const UPDATE_WINDOW_SCROLL_POSITION = 'app/ArchivePage/UPDATE_WINDOW_SCROLL_POSITION';
export const SCROLLING_ADDRESS_CHANGE = 'app/ArchivePage/SCROLLING_ADDRESS_CHANGE';
export const AUTOSCROLLTOPOST = 'app/ArchivePage/AUTOSCROLLTOPOST'
export const ZERO_ARCHIVESTACK = 'app/ArchivePage/ZERO_ARCHIVESTACK';
export const DEDUCE_CURRENTLYDISPLAYED_ITEMINDEX = 'app/ArchivePage/DEDUCE_CURRENTLYDISPLAYED_ITEMINDEX';
export const SET_LEADERBOARDINDEX = 'app/ArchivePage/SET_LEADERBOARDINDEX';
export const REGULAR_CHUNKSIZE = 10;
export const FEATURED_CHUNKSIZE = 3;
export const COMBINEDHEROANDREGULAR_CHUNKSIZE = 10;

export const SET_FORCE_RENDER = 'app/ArchivePage/SET_FORCE_RENDER';
export const BOTTOMOFSTACKREACHED = 'app/ArchivePage/BOTTOMOFSTACKREACHED';

export const DEFAULT_ACTION = 'app/ArchivePage/DEFAULT_ACTION';
