export const SET_LEADERBOARDINDEX = 'app/LeaderboardHolder/SET_SIDEBARINDEX';
export const SET_LEADERBOARD_DISPLAYDATA = 'app/LeaderboardHolder/SET_LEADERBOARD_DISPLAYDATA';
export const SET_LEADERBOARDSAFETY = 'app/LeaderboardHolder/SET_LEADERBOARDSAFETY';
export const START_ADREFRESHTIMER = 'app/LeaderboardHolder/START_ADREFRESHTIMER';
export const AD_LEADERBOARD_JUSTFIRED = 'app/LeaderboardHolder/AD_LEADERBOARD_JUSTFIRED';
export const SET_LEADERBOARD_TIMERSAFETY = 'app/LeaderboardHolder/SET_LEADERBOARD_TIMERSAFETY';
export const SET_LEADERBOARD_CONTENTSAFETY = 'app/LeaderboardHolder/SET_LEADERBOARD_CONTENTSAFETY';
