export const SET_INTERSTITIALINDEX = 'app/InterstitialAdHolder/SET_INTERSTITIALINDEX';
export const SET_INTERSTITIAL_DISPLAYDATA = 'app/InterstitialAdHolder/SET_INTERSTITIAL_DISPLAYDATA';

export const SET_INTERSTITIALSAFETY = 'app/InterstitialAdHolder/SET_INTERSTITIALSAFETY';
export const START_ADREFRESHTIMER = 'app/InterstitialAdHolder/START_ADREFRESHTIMER';
export const AD_INTERSTITIAL_JUSTFIRED = 'app/InterstitialAdHolder/AD_INTERSTITIAL_JUSTFIRED';
