export const LOAD_FEATUREDPOPULARTRENDING = 'ez2/Home/FeaturedPoularTrending/LOAD_FEATUREDPOPULARTRENDING';
export const LOAD_FEATUREDPOPULARTRENDING_SUCCESS = 'ez2/Home/FeaturedPoularTrending/LOAD_FEATUREDPOPULARTRENDING_SUCCESS';
export const LOAD_FEATUREDPOPULARTRENDING_FAILURE = 'ez2/Home/FeaturedPoularTrending/LOAD_FEATUREDPOPULARTRENDING_FAILURE';
