/*
 *
 * SinglePostPage constants
 *
 */

export const SET_CURRENTLYDISPLAYEDITEMINDEX = 'app/SinglePostPage/SET_CURRENTLYDISPLAYEDITEMINDEX';
export const SET_CURRENTLYDISPLAYEDITEMINDEXWAYPOINTINITIATED = 'app/SinglePostPage/SET_CURRENTLYDISPLAYEDITEMINDEXWAYPOINTINITIATED';
export const RESET_CURRENTLYDISPLAYEDITEMINDEXWAYPOINTINITIATED = 'app/SinglePostPage/RESET_CURRENTLYDISPLAYEDITEMINDEXWAYPOINTINITIATED';
export const UPDATE_WINDOW_SCROLL_POSITION = 'app/SinglePostPage/UPDATE_WINDOW_SCROLL_POSITION';
export const SCROLLING_ADDRESS_CHANGE = 'app/SinglePostPage/SCROLLING_ADDRESS_CHANGE';
export const AUTOSCROLLTOPOST = 'app/SinglePostPage/AUTOSCROLLTOPOST'
export const ZERO_POSTSTACK = 'app/SinglePostPage/ZERO_POSTSTACK';
export const DEDUCE_CURRENTLYDISPLAYED_ITEMINDEX = 'app/SinglePostPage/DEDUCE_CURRENTLYDISPLAYED_ITEMINDEX';
export const SET_LEADERBOARDINDEX = 'app/SinglePostPage/SET_LEADERBOARDINDEX';
export const ARRIVINGFORFIRSTTIME = 'app/SinglePostPage/ARRIVINGFORFIRSTTIME';
export const ADD_WAYPOINTTOVIEWPORT = 'app/SinglePostPage/ADD_WAYPOINTTOVIEWPORT';
export const REMOVE_WAYPOINTFROMVIEWPORT = 'app/SinglePostPage/REMOVE_WAYPOINTFROMVIEWPORT';
export const SET_CURRENTPOSTSTACKDISPLAYDATA = 'app/SinglePostPage/SET_CURRENTPOSTSTACKDISPLAYDATA';
export const BOTTOMOFSTACKREACHED = 'app/SinglePostPage/BOTTOMOFSTACKREACHED';
export const SET_FORCE_RENDER = 'app/SinglePostPage/SET_FORCE_RENDER';
export const SET_DISPLAYEDPOSTSTACK = 'app/SinglePostPage/SET_DISPLAYEDPOSTSTACK';

export const DEFAULT_ACTION = 'app/SinglePostPage/DEFAULT_ACTION';
